

-- SELECT setval(
--     pg_get_serial_sequence('students', 'id'), 
--     COALESCE(MAX(id), 0)
-- ) 
-- FROM students;

-- SELECT setval(
--     pg_get_serial_sequence('students', 'id'), 
--     COALESCE(MAX(id), 0) + 1, 
--     false
-- ) 
-- FROM students;

-- ALTER TABLE students 
--   ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- INSERT INTO students (name, email, age)
-- VALUES ('Bob','bob@gmail.com',-23)